spring:
  application:
    name: notification-backend

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}  # Bu değişkenlerin doğru olduğundan emin ol
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-ui.html
