spring:
  application:
    name: notification-backend

  mail:
    host: smtp.gmail.com
    port: 587
    username: ustundagnonik@gmail.com
    password: ozannisa0418
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-ui.html

logging:
  file:
    path: ./logs
  level:
    root: DEBUG
    org.springframework: DEBUG
